services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env

  tester:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    env_file: .env
    command: go test -v
